# Random Sampling with Numpy

for generating random data we use random sampling

In [3]:
import numpy as np
import random 

for generating random values we use random function and this gives you value between 0 to 1.

In [5]:
np.random.random(1)

array([0.35154667])

for generating random 2d array

In [6]:
np.random.random((3,3))

array([[0.32508449, 0.04675998, 0.17571244],
       [0.23115831, 0.51015922, 0.72651997],
       [0.16704811, 0.94205656, 0.16073717]])

for genrating single integar value we use randin() function.

In [7]:
np.random.randint(1,4)

2

for generating 2d array

In [9]:
np.random.randint(1,4,(4,4))

array([[2, 3, 2, 1],
       [2, 3, 3, 1],
       [2, 1, 3, 1],
       [1, 3, 3, 3]])

for generating n_d array

In [11]:
np.random.randint(1,4,(2,4,4))

array([[[2, 1, 3, 3],
        [3, 3, 1, 2],
        [3, 1, 3, 1],
        [1, 3, 3, 3]],

       [[1, 3, 3, 2],
        [3, 1, 1, 1],
        [1, 1, 1, 3],
        [2, 1, 3, 1]]])

In [13]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [14]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

range of seed() function-------------------------

In [16]:
2**32-1

4294967295

rand() function gives value in the range of 0 to 1

In [17]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [18]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

randn() this function gives you negative and positive vlaues

In [20]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [23]:
x=[1,2,3]
np.random.choice(x)

1

In [24]:
x=[1,2,3]
np.random.choice(x)

1

In [25]:
x=[1,2,3]
np.random.choice(x)

2

In [26]:
for i in range(20):
    print(np.random.choice(x))

1
1
1
3
1
3
3
1
2
1
2
3
3
2
3
3
1
1
1
1


permutation

In [27]:
np.random.permutation(x)

array([2, 1, 3])

In [28]:
np.random.permutation(x)

array([1, 3, 2])