In [1]:
import numpy as np

In [2]:
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
mx_1s=np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [4]:
mx_1s.dtype

dtype('float64')

In [5]:
mx_1s=np.ones((4,5))
print(mx_1s)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
mx_1s=np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
mx_0s=np.zeros((3,4))
print(mx_0s)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
mx_0s=np.zeros((3,4),dtype=int)
print(mx_0s)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
mx_0s=np.zeros((3,4),dtype=bool)
print(mx_0s)

[[False False False False]
 [False False False False]
 [False False False False]]


In [14]:
mx_0s=np.zeros((3,4),dtype=str)
print(mx_0s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [15]:
em_str =' '
print(bool(em_str))

True


In [16]:
em_mx=np.empty((3,3))
print(em_mx)

[[0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 6.0868888e-321]
 [8.4560344e-307 1.2461147e-306 0.0000000e+000]]
